### ISSUE TITLE
StringBuilder问题

### ISSUE THREAD

**Issue by qianjl-star** [cnJun/java-les-001#1]
示例3中：
long start = System.currentTimeMillis();
String str = "";
for (int i = 0; i < 50000; i++) {
str += i;
}
System.out.println(str.length());
System.out.println("耗时：" + (System.currentTimeMillis() - start) + "ms");
JVM优化后：
long start = System.currentTimeMillis();
String str = "";
for (int i = 0; i < 50000; i++) {
StringBuilder tmp = new StringBuilder();
此处不应该为在新的对象中增加字符串吗，为什么还是在第一个创建的里面增加？
JVM不是会自动优化吗，为什么上面的示例中没有优化？
tmp.append(str);
tmp.append(i);
str = tmp.toString();
}
System.out.println(str.length());
System.out.println("耗时：" + (System.currentTimeMillis() - start) + "ms");

**Comment by cnJun** [comment]
对于循环内使用 `+` 进行字符串拼接的操作，JVM 每次会 new 一个 StringBuilder，然后调用 append 方法，拼接完成后调用 toString。

Java 版本不同对字符串的优化细节也不一样。比如 Java 9 中改为了 invokedynamic。

**Comment by qianjl-star** [comment]
在不断new对象的时候，append不应该是将字符串添加到新建的对象后面吗？为什么最后字符串感觉全部添加到一个对象中了？
JVM会自动优化，也就是说程序最后运行的代码应该是相同的，那为什么运行后还会有优化前和优化后的区别？

**Comment by cnJun** [comment]
因为每个版本 JVM 的优化细节上有些不一样。按照它优化的方式，我们写出来的等效的代码。
这个等效的代码生成的字节码和 JVM 优化后生成的字节码不一定会是一模一样，因此执行时间上会有一些差异，但差异不大。
![a1](https://user-images.githubusercontent.com/195026/70680763-2c4b5380-1cd4-11ea-8265-4da8fd2ebe36.jpg)
![a2](https://user-images.githubusercontent.com/195026/70680789-38cfac00-1cd4-11ea-9a85-e7bfb02874b6.jpg)
